### ISSUE TITLE
install-iml-local encounters errors but still continues

### ISSUE THREAD

**Issue by mkpankov** [whamcloud/integrated-manager-for-lustre#1501]
```
    adm: Transaction Summary
    adm: ================================================================================
    adm: Install  1 Package (+16 Dependent packages)
    adm: Total download size: 14 M
    adm: Installed size: 59 M
    adm: Downloading packages:
    adm: https://copr-be.cloud.fedoraproject.org/results/managerforlustre/buildtools/epel-7-x86_64/01152137-rpmdevtools/rpmdevtools-8.10-7.el8.noarch.rpm: [Errno 14] HTTPS Error 404 - Not Found
    adm: Trying other mirror.
    adm: To address this issue please refer to the below wiki article 
    adm: 
    adm: https://wiki.centos.org/yum-errors
    adm: 
    adm: If above article doesn't help to resolve this issue please use https://bugs.centos.org/.
    adm: 
    adm: 
    adm: Error downloading packages:
    adm:   rpmdevtools-8.10-7.el8.noarch: [Errno 256] No more mirrors to try.
    adm: info: downloading installer
    adm: info: profile set to 'default'
    adm: info: default host triple is x86_64-unknown-linux-gnu
    adm: info: updating existing rustup installation
    adm: 
    adm: Rust is installed now. Great!
    adm: 
    adm: To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH
    adm: environment variable. Next time you log in this will be done
    adm: automatically.
    adm: 
    adm: To configure your current shell run source $HOME/.cargo/env
    adm: /tmp/vagrant-shell: line 13: rpmdev-bumpspec: command not found
    adm: /tmp/vagrant-shell: line 14: rpmdev-bumpspec: command not found
    adm: /tmp/vagrant-shell: line 20: rpmspec: command not found
    adm: /tmp/vagrant-shell: line 21: rpmdev-bumpspec: command not found
    adm: make -f .copr/Makefile srpm outdir=.
    adm: make[1]: Entering directory `/integrated-manager-for-lustre'
    adm: mkdir -p /tmp/tmp.fH5UkUNhjF/_topdir/{SOURCES,SPECS}
    adm: mkdir -p /tmp/tmp.fH5UkUNhjF/release/rust-iml
    adm: cargo build --release
    adm:  Downloading crates ...
    adm:   Downloaded pin-project-lite v0.1.4
```

This is `scanner` branch, containing `device-scanner-plugin` and current `master`.

```commit 5179d17245e2bab03995e69bdbe463a20946b279
Merge: 79aa75e fbacdf7
Author: Michael Pankov <work@michaelpankov.com>
Date:   Tue Jan 21 10:04:03 2020 +0300

    Merge branch 'master' into scanner
    
    Signed-off-by: Michael Pankov <work@michaelpankov.com>
```

Suggested behaviour: abort on first error.
