### ISSUE TITLE
Can't build `list` branch

### ISSUE THREAD

**Issue by mkpankov** [whamcloud/integrated-manager-for-lustre#2208]
It's rebased onto `ip1981/ex-1510-snap-list-daemon`.

```
    adm: make -f .copr/Makefile iml-gui-srpm outdir=.
    adm: make[2]: Entering directory `/iml'
    adm: mkdir -p /tmp/tmp.C2XCigZDH9/_topdir/{SOURCES,SPECS}
    adm: curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
    adm: [yarn]
    adm: name=Yarn Repository
    adm: baseurl=https://dl.yarnpkg.com/rpm/
    adm: enabled=1
    adm: gpgcheck=1
    adm: gpgkey=https://dl.yarnpkg.com/rpm/pubkey.gpg
    adm: curl --silent --location https://rpm.nodesource.com/setup_12.x | bash -
    adm: 
    adm: ## Installing the NodeSource Node.js 12.x repo...
    adm: 
    adm: ## Inspecting system...
    adm: 
    adm: + rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
    adm: + uname -m
    adm: 
    adm: ## Confirming "el7-x86_64" is supported...
    adm: 
    adm: + curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_12.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'
    adm: 
    adm: ## Downloading release setup RPM...
    adm: 
    adm: + mktemp
    adm: + curl -sL -o '/tmp/tmp.VaS8VuanRl' 'https://rpm.nodesource.com/pub_12.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'
    adm: 
    adm: ## Installing release setup RPM...
    adm: 
    adm: + rpm -i --nosignature --force '/tmp/tmp.VaS8VuanRl'
    adm: 
    adm: ## Cleaning up...
    adm: 
    adm: + rm -f '/tmp/tmp.VaS8VuanRl'
    adm: 
    adm: ## Checking for existing installations...
    adm: 
    adm: + rpm -qa 'node|npm' | grep -v nodesource
    adm: 
    adm: ## Run `sudo yum install -y nodejs` to install Node.js 12.x and npm.
    adm: ## You may also need development tools to build native addons:
    adm:      sudo yum install gcc-c++ make
    adm: ## To install the Yarn package manager, run:
    adm:      curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
    adm:      sudo yum install yarn
    adm: yum install -y yarn
    adm: make[2]: yum: Command not found
    adm: make[2]: *** [iml-gui-srpm] Error 127
    adm: make[2]: Leaving directory `/iml'
    adm: make[1]: Leaving directory `/iml'
    adm: make[1]: *** [iml-gui-rpm] Error 2
    adm: make: *** [local] Error 2
    adm: Finish: shell
    adm: INFO: mock.py version 1.2.17 starting (python version = 2.7.5)...
    adm: Start: init plugins
    adm: INFO: selinux disabled
    adm: Finish: init plugins
    adm: Start: run
    adm: Start: chroot init
    adm: INFO: calling preinit hooks
    adm: INFO: enabled root cache
    adm: INFO: enabled yum cache
    adm: Start: cleaning yum metadata
    adm: Finish: cleaning yum metadata
    adm: Mock Version: 1.2.17
    adm: INFO: Mock Version: 1.2.17
    adm: WARNING: For multilib systems, both architectures of nosync library need to be installed
    adm: Finish: chroot init
    adm: INFO: copying /var/lib/mock/epel-7-x86_64/root/iml/_topdir to /tmp/iml/_topdir
    adm: Finish: run
    adm: INFO: mock.py version 1.2.17 starting (python version = 2.7.5)...
    adm: Start: init plugins
    adm: INFO: selinux disabled
    adm: Finish: init plugins
    adm: Start: run
    adm: Start: chroot init
    adm: INFO: calling preinit hooks
    adm: INFO: enabled root cache
    adm: INFO: enabled yum cache
    adm: Start: cleaning yum metadata
    adm: Finish: cleaning yum metadata
    adm: Mock Version: 1.2.17
    adm: INFO: Mock Version: 1.2.17
    adm: WARNING: For multilib systems, both architectures of nosync library need to be installed
    adm: Finish: chroot init
    adm: INFO: copying /var/lib/mock/epel-7-x86_64/root/iml/chroma_support.repo to /tmp/iml/
    adm: Finish: run
    adm: Last login: Wed Sep  2 11:38:18 UTC 2020
    adm: ++ rm -rf /tmp/manager-rpms /tmp/agent-rpms
    adm: ++ mkdir -p /tmp/manager-rpms /tmp/agent-rpms
    adm: ++ cp /tmp/iml/_topdir/RPMS/rust-iml-action-runner-0.3.0-10.1599047505.x86_64.rpm /tmp/iml/_topdir/RPMS/rust-iml-agent-comms-0.3.0-10.1599047505.x86_64.rpm /tmp/iml/_topdir/RPMS/rust-iml-api-0.3.0-10.1599047505.x86_64.rpm /tmp/iml/_topdir/RPMS/rust-iml-cli-0.3.0-10.1599047505.x86_64.rpm /tmp/iml/_topdir/RPMS/rust-iml-corosync-0.3.0-10.1599047505.x86_64.rpm /tmp/iml/_topdir/RPMS/rust-iml-config-cli-0.3.0-10.1599047505.x86_64.rpm /tmp/iml/_topdir/RPMS/rust-iml-journal-0.3.0-10.1599047505.x86_64.rpm /tmp/iml/_topdir/RPMS/rust-iml-mailbox-0.3.0-10.1599047505.x86_64.rpm /tmp/iml/_topdir/RPMS/rust-iml-ntp-0.3.0-10.1599047505.x86_64.rpm /tmp/iml/_topdir/RPMS/rust-iml-ostpool-0.3.0-10.1599047505.x86_64.rpm /tmp/iml/_topdir/RPMS/rust-iml-postoffice-0.3.0-10.1599047505.x86_64.rpm /tmp/iml/_topdir/RPMS/rust-iml-report-0.3.0-10.1599047505.x86_64.rpm /tmp/iml/_topdir/RPMS/rust-iml-sfa-0.3.0-10.1599047505.x86_64.rpm '/tmp/iml/_topdir/RPMS/rust-iml-snapshot-*.rpm' /tmp/iml/_topdir/RPMS/rust-iml-stats-0.3.0-10.1599047505.x86_64.rpm /tmp/iml/_topdir/RPMS/rust-iml-task-runner-0.3.0-10.1599047505.x86_64.rpm /tmp/iml/_topdir/RPMS/rust-iml-device-0.3.0-10.1599047505.x86_64.rpm /tmp/iml/_topdir/RPMS/rust-iml-warp-drive-0.3.0-10.1599047505.x86_64.rpm /tmp/manager-rpms/
    adm: cp: cannot stat ‘/tmp/iml/_topdir/RPMS/rust-iml-snapshot-*.rpm’: No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

```

Looks like there are two different issues.
