### ISSUE TITLE
IML 4.0.9.0 Manual Testing

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#767]
Results for the following IML 4.0.9.0 tests will be documented in this issue:
1. managed ldiskfs
1. managed zfs
1. managed lidskfs and zfs mixed
1. monitored ldiskfs
1. monitored zfs

**Comment by jgrund** [comment]
Of note, we are fixing these issues in #766, and everything except pcappy hanging (which needs to be reproduced) should be addressed.

**Comment by liy106** [comment]
Managed Ldiskfs: 
Finally passed, but hit and resolved the following issues during the test
1. Since the versions of fence-agents-common on the nodes were not compatible, power control can't be configured correctly. This issue will be fixed by https://github.com/whamcloud/fence-agents-vbox/pull/2.
2. lustre client can't be mounted after installing lustre client rpm packages, due to the following error:
```
# mount -t lustre 10.73.20.12@tcp0:10.73.20.11@tcp0:/fs /mnt/fs
mount.lustre: mount 10.73.20.12@tcp0:10.73.20.11@tcp0:/fs at /mnt/fs failed: No such device
Are the lustre modules loaded?
Check /etc/modprobe.conf and /proc/filesystems
```
This issue can be resolved by rebooting client node.

**Comment by liy106** [comment]
Managed ZFS: passed without any issue

**Comment by liy106** [comment]
Monitored ldiskfs: passed, with the following message when configuring lnet
```
mds1::
del:
    - net:
          errno: -2
          descr: "cannot del network: No such file or directory"
add:
    - net:
          errno: -22
          descr: "cannot add network: Invalid argument"
```
